server:
  port: 8081
  servlet:
    context-path: /vineApp/api
  tomcat:
    accesslog:
      enabled: true
      pattern: '{"remoteIP": "%a", "localIP": "%A", "clientHost": "%h", "protocol": "%H", "requestMethod": "%m", "requestURL": "%r", "statusCode": "%s", "elapsedTime": "%D", "responseTime": "%F", "date": "%t{dd MMM yyyy HH:mm:ss,SSS}", "user": "%u", "requestURI": "%U", "server": "%v", "spanID": "%{x-b3-spanid}i", "traceID": "%{x-b3-traceid}i", "parentSpanID": "%{parentspanid}i", "traceParentID": "%{traceparent}i"}'
      prefix: access-log
      suffix: .log
      max-days: 5
      rename-on-rotate: true
  # Enable graceful shutdown
  shutdown: graceful

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
spring:
  #security:
   # oauth2:
      #resourceserver:
       # jwt:
          #issuer-uri: http://localhost:9022/auth/realms/healthcare-portal-private
          #jwk-set-uri: http://localhost:9022/auth/realms/healthcare-portal-private/protocol/openid-connect/certs
          # for local use: commment issuer-uri and set jwk-set-uri: http://localhost:9999/certs
  profiles:
    include: common
  banner:
    location: classpath:/banner-dev.txt
  session:
    store-type: none
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: vineApp
      maximum-pool-size: 10
      connection-timeout: 5000
  jpa:
    hibernate:
      # for now is set to 'update' (Hibernate create and update new tables and columns),
      # later change to 'validate' (Hibernate only validates whether the tables and columns exist; otherwise, it throws an exception)
      ddl-auto: update
    show-sql: true

swagger:
  title: ^project.name^
  description: ^project.description^
  version: ^project.version^
  termsOfServiceUrl: \#
  contactName: Ivor Gradiski-Zrinski
  contactUrl: \#
  contactEmail: mail@mail.com
  license: License of API
  licenseUrl: \#

vineApp:
  refTokDuration: 600000
  jwtSecret: Gemistarka
  jwtExpiration: 600000
