-- MySQL Script generated by MySQL Workbench
-- Wed Sep 22 18:54:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VineAppDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VineAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VineAppDB` DEFAULT CHARACTER SET utf8 ;
USE `VineAppDB` ;

-- -----------------------------------------------------
-- Table `VineAppDB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `SURNAME` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(250) NOT NULL,
  `AKTIVAN` INT NULL,
  `LAST_LOGIN` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`USER_ROLE` (
  `USER_ID` INT NOT NULL,
  `ROLE_ID` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATETIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_USER_has_ROLE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `VineAppDB`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_ROLE_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `VineAppDB`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
