-- MySQL Script generated by MySQL Workbench
-- Fri Oct  8 09:14:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VineAppDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VineAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VineAppDB` DEFAULT CHARACTER SET utf8 ;
USE `VineAppDB` ;

-- -----------------------------------------------------
-- Table `VineAppDB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `SURNAME` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(250) NOT NULL,
  `AKTIVAN` INT NULL,
  `LAST_LOGIN` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`ROLE` (
  `ID` INT GENERATED ALWAYS AS () STORED,
  `ROLE_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`USER_ROLE` (
  `USER_ID` INT NOT NULL,
  `ROLE_ID` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATETIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_has_ROLE_ROLE1_idx` (`ROLE_ID` ASC) VISIBLE,
  INDEX `fk_USER_has_ROLE_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_ROLE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `VineAppDB`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_ROLE_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `VineAppDB`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`REFRESH_TOKEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`REFRESH_TOKEN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(250) NULL,
  `expiryDate` DATETIME NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_REFRESH_TOKEN_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_REFRESH_TOKEN_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `VineAppDB`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`TIP_ZASTITNOG_SREDSTVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`TIP_ZASTITNOG_SREDSTVA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kategorija` VARCHAR(60) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`ZASTITNO_SREDSTVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`ZASTITNO_SREDSTVO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `TIP_ZASTITNOG_SREDSTVA_id` INT NOT NULL,
  `Description` VARCHAR(200) NULL,
  `Composition` VARCHAR(45) NULL,
  `Group` VARCHAR(45) NULL,
  `Formulation` VARCHAR(45) NULL,
  `Type_of_action` VARCHAR(45) NULL,
  `Usage` VARCHAR(45) NULL,
  `Concentration` DECIMAL(10) NULL,
  `Dosage_on_100` DECIMAL(10) NULL,
  `approved` INT NOT NULL,
  `waiting` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ZASTITNO_SREDSTVO_TIP_ZASTITNOG_SREDSTVA1_idx` (`TIP_ZASTITNOG_SREDSTVA_id` ASC) VISIBLE,
  CONSTRAINT `fk_ZASTITNO_SREDSTVO_TIP_ZASTITNOG_SREDSTVA1`
    FOREIGN KEY (`TIP_ZASTITNOG_SREDSTVA_id`)
    REFERENCES `VineAppDB`.`TIP_ZASTITNOG_SREDSTVA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`BOLEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`BOLEST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`FENOZAFA_RAZVOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`FENOZAFA_RAZVOJA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `time_of_usage` VARCHAR(45) NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`BOLEST_has_faza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`BOLEST_has_faza` (
  `BOLEST_id` INT NOT NULL,
  `FENOZAFA_RAZVOJA_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BOLEST_has_FENOZAFA_RAZVOJA_FENOZAFA_RAZVOJA1_idx` (`FENOZAFA_RAZVOJA_id` ASC) VISIBLE,
  INDEX `fk_BOLEST_has_FENOZAFA_RAZVOJA_BOLEST1_idx` (`BOLEST_id` ASC) VISIBLE,
  CONSTRAINT `fk_BOLEST_has_FENOZAFA_RAZVOJA_BOLEST1`
    FOREIGN KEY (`BOLEST_id`)
    REFERENCES `VineAppDB`.`BOLEST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOLEST_has_FENOZAFA_RAZVOJA_FENOZAFA_RAZVOJA1`
    FOREIGN KEY (`FENOZAFA_RAZVOJA_id`)
    REFERENCES `VineAppDB`.`FENOZAFA_RAZVOJA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VineAppDB`.`SREDSTVO_HAS_BOLEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VineAppDB`.`SREDSTVO_HAS_BOLEST` (
  `ZASTITNO_SREDSTVO_id` INT NOT NULL,
  `BOLEST_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  INDEX `fk_ZASTITNO_SREDSTVO_has_BOLEST_BOLEST1_idx` (`BOLEST_id` ASC) VISIBLE,
  INDEX `fk_ZASTITNO_SREDSTVO_has_BOLEST_ZASTITNO_SREDSTVO1_idx` (`ZASTITNO_SREDSTVO_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ZASTITNO_SREDSTVO_has_BOLEST_ZASTITNO_SREDSTVO1`
    FOREIGN KEY (`ZASTITNO_SREDSTVO_id`)
    REFERENCES `VineAppDB`.`ZASTITNO_SREDSTVO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZASTITNO_SREDSTVO_has_BOLEST_BOLEST1`
    FOREIGN KEY (`BOLEST_id`)
    REFERENCES `VineAppDB`.`BOLEST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
